#!/bin/bash

# fixing date + avoid hitting something big
custom_month=$(date +%b)
custom_hour=$(date +%H)
custom_day=$(date +%e)
custom_path_to_log=/var/log/syslog

# Nagios exit levels:
OK=0
WARN=1
ERROR=2
UNKNOWN=3

# Help
function help
{
        echo "Help: Count blocked IP addresses by comment. Arguments:
        -w --Warning threshold (NUM)
        -c --Critical threshold (NUM)"
}

# Parse input parameters
until [ -z "$1" ]; do

  case "$1" in
    -w|--warnlevel)
                WARNLEVEL="$2"
                shift
                ;;
    -c|--criticallevel)
                CRITLEVEL="$2"
                shift
                ;;
   *)
                help
                exit 1
                ;;
  esac
  shift
done

# Check if everyting in input is okay
if [[ -z "$WARNLEVEL" ]] || [[ -z "$CRITLEVEL" ]]
 then
        echo "Missing argument"
        help
        exit 1
 fi

# Get information from exim
STATUS=$(grep "oom" $PATH_TO_LOG | grep -e "$MONTH  $DAY $HOUR")

# If result is less than warning threshold - OK
if [ "$STATUS" -lt "$WARNLEVEL" ];then
        echo "OK - $STATUS messages on queue"
        exit $OK
fi

# If result is greater than threshold and less than critical threshold - WARNING
if [ "$STATUS" -gt "$WARNLEVEL" -a "$STATUS" -lt "$CRITLEVEL" ];then
        echo "WARNING - $STATUS messages on queue $LABEL"
        exit $WARN
fi

# If result is greater than critical threshold - CRITICAL
if [ "$STATUS" -gt "$CRITLEVEL" ];then
        echo "CRITICAL - $STATUS messages on queue $LABEL"
        exit $ERROR
fi

# If something else is not okay - UNKNOWN (shitty orange)
echo "UNKNOWN ERROR status ($STATUS)!"
exit $UNKNOWN

