#!/bin/bash

# Nagios exit levels:
OK=0
WARN=1
ERROR=2
UNKNOWN=3

# Help
function help
{
        echo "Help: Count blocked IP addresses by comment. Arguments:
        -w --Warning threshold (NUM)
        -c --Critical threshold (NUM)
        -M LABEL"
}

# Parse input parameters
until [ -z "$1" ]; do

  case "$1" in
    -w|--warnlevel)
                WARNLEVEL="$2"
                shift
                ;;
    -c|--criticallevel)
                CRITLEVEL="$2"
                shift
                ;;
    -M)
                M="$2"
                shift
                ;;
    *)
                help
                exit 1
                ;;
  esac
  shift
done

# Check if everyting in input is okay
if [[ -z "$WARNLEVEL" ]] || [[ -z "$CRITLEVEL" ]] || [[ -z "$M" ]]
 then
        echo "Missing argument"
        help
        exit 1
 fi

# Get information from exim
STATUS=$(sudo /usr/sbin/$M -bpc)

# Perfdata:
LABEL="| ${M}=${STATUS};$WARNLEVEL;$CRITLEVEL;0;"

# If result is less than warning threshold - OK
if [ "$STATUS" -lt "$WARNLEVEL" ];then
        echo "OK - $STATUS messages on queue $LABEL"
        exit $OK
fi

# If result is greater than threshold and less than critical threshold - WARNING
if [ "$STATUS" -gt "$WARNLEVEL" -a "$STATUS" -lt "$CRITLEVEL" ];then
        echo "WARNING - $STATUS messages on queue $LABEL"
        exit $WARN
fi

# If result is greater than critical threshold - CRITICAL
if [ "$STATUS" -gt "$CRITLEVEL" ];then
        echo "CRITICAL - $STATUS messages on queue $LABEL"
        exit $ERROR
fi

# If something else is not okay - UNKNOWN (shitty orange)
echo "UNKNOWN ERROR status ($STATUS)!"
exit $UNKNOWN

